### ISSUE TITLE
插件安装失败

### ISSUE THREAD

**Issue by Smalldy** [PyQt5/QSSEditor#1]
![image](https://user-images.githubusercontent.com/14820063/215311851-eaa84dcf-57d9-4801-990c-0c6515cadca9.png)

![image](https://user-images.githubusercontent.com/14820063/215311906-1dbbd85c-816e-4cef-9f77-f86d3ec47e0f.png)

**Comment by 892768447** [comment]
提供的编译包只支持长期版本的Qt，你可以尝试用 5.12.12的试试。

QSSEditor_ubuntu-18.04_5.12.12_gcc_64.zip
QSSEditor_ubuntu-18.04_5.15.2_gcc_64.zip
QSSEditor_ubuntu-18.04_5.9.9_gcc_64.zip
QSSEditor_ubuntu-20.04_5.12.12_gcc_64.zip
QSSEditor_ubuntu-20.04_5.15.2_gcc_64.zip
QSSEditor_ubuntu-20.04_5.9.9_gcc_64.zip
QSSEditor_ubuntu-20.04_6.2.4_gcc_64.zip
QSSEditor_ubuntu-22.04_5.12.12_gcc_64.zip
QSSEditor_ubuntu-22.04_5.15.2_gcc_64.zip
QSSEditor_ubuntu-22.04_5.9.9_gcc_64.zip
QSSEditor_ubuntu-22.04_6.2.4_gcc_64.zip

**Comment by Smalldy** [comment]
很遗憾 并不能兼容 :(

**Comment by 892768447** [comment]
> 很遗憾 并不能兼容 :(

你可以重新安装一下Qt

```
sudo pip3 install aqtinstall

cd ~

aqt install-qt linux desktop 5.15.2 gcc_64
```

```
export LD_LIBRARY_PATH=~/5.15.2/gcc_64/lib
cd ~/5.15.2/gcc_64/bin
./designer
```

**Comment by 892768447** [comment]
修复了编译时候库路径加载问题。你可以试试

[QSSEditor_ubuntu-18.04_5.12.12_gcc_64.zip.zip](https://github.com/PyQt5/QSSEditor/files/10543160/QSSEditor_ubuntu-18.04_5.12.12_gcc_64.zip.zip)
[QSSEditor_ubuntu-20.04_5.12.12_gcc_64.zip.zip](https://github.com/PyQt5/QSSEditor/files/10543161/QSSEditor_ubuntu-20.04_5.12.12_gcc_64.zip.zip)
[QSSEditor_ubuntu-22.04_5.12.12_gcc_64.zip.zip](https://github.com/PyQt5/QSSEditor/files/10543162/QSSEditor_ubuntu-22.04_5.12.12_gcc_64.zip.zip)

**Comment by Smalldy** [comment]
> 修复了编译时候库路径加载问题。你可以试试
> 
> [QSSEditor_ubuntu-18.04_5.12.12_gcc_64.zip.zip](https://github.com/PyQt5/QSSEditor/files/10543160/QSSEditor_ubuntu-18.04_5.12.12_gcc_64.zip.zip) [QSSEditor_ubuntu-20.04_5.12.12_gcc_64.zip.zip](https://github.com/PyQt5/QSSEditor/files/10543161/QSSEditor_ubuntu-20.04_5.12.12_gcc_64.zip.zip) [QSSEditor_ubuntu-22.04_5.12.12_gcc_64.zip.zip](https://github.com/PyQt5/QSSEditor/files/10543162/QSSEditor_ubuntu-22.04_5.12.12_gcc_64.zip.zip)

感谢，问题已解决，可以正常使用了。
![image](https://user-images.githubusercontent.com/14820063/215680379-67eb3ceb-ab90-4a04-a698-ef97e27c8e51.png)
